/**
 * Pictogram catalog entries — shared between browser and CLI.
 */
(function (root) {
  root.MemoryEngineCatalogEntries = [
    { id: 'CAT-0001', hebrew: 'סבא', concept: 'Grandfather', provisional: false, provisionalNote: '', strategy: 'Direct Iconic Representation' },
    { id: 'CAT-0002', hebrew: 'סבתא', concept: 'Grandmother', provisional: false, provisionalNote: '', strategy: 'Direct Iconic Representation' },
    { id: 'CAT-0003', hebrew: 'ילדה', concept: 'Girl / Young girl', provisional: false, provisionalNote: '', strategy: 'Direct Iconic Representation' },
    { id: 'CAT-0004', hebrew: 'ילד', concept: 'Boy / Young boy', provisional: false, provisionalNote: '', strategy: 'Direct Iconic Representation' },
    { id: 'CAT-0005', hebrew: 'לילה', concept: 'Night', provisional: false, provisionalNote: '', strategy: 'Established Convention' },
    { id: 'CAT-0006', hebrew: 'נדנדה', concept: 'Swing', provisional: false, provisionalNote: '', strategy: 'Direct Iconic Representation' },
    { id: 'CAT-0007', hebrew: 'בקבוק חם', concept: 'Hot bottle / Thermos', provisional: false, provisionalNote: '', strategy: 'Direct Iconic Representation' },
    { id: 'CAT-0008', hebrew: 'נסענו', concept: 'Traveling / We traveled', provisional: true, provisionalNote: 'Verb form — concept label requires confirmation: represents journey/travel', strategy: 'Direct Iconic Representation' },
    { id: 'CAT-0009', hebrew: 'יום הולדת', concept: 'Birthday', provisional: false, provisionalNote: '', strategy: 'Compositional Representation' },
    { id: 'CAT-0010', hebrew: 'אולר', concept: 'Penknife / Pocket knife', provisional: false, provisionalNote: '', strategy: 'Direct Iconic Representation' },
    { id: 'CAT-0011', hebrew: 'קוף', concept: 'Monkey', provisional: false, provisionalNote: '', strategy: 'Direct Iconic Representation' },
    { id: 'CAT-0012', hebrew: 'מתנה', concept: 'Gift / Present', provisional: false, provisionalNote: '', strategy: 'Direct Iconic Representation' },
    { id: 'CAT-0013', hebrew: 'בוקר', concept: 'Morning', provisional: false, provisionalNote: '', strategy: 'Established Convention' },
    { id: 'CAT-0014', hebrew: 'עיתון', concept: 'Newspaper', provisional: false, provisionalNote: '', strategy: 'Direct Iconic Representation' },
    { id: 'CAT-0015', hebrew: 'בית ספר', concept: 'School', provisional: false, provisionalNote: '', strategy: 'Metonymic Association' },
    { id: 'CAT-0016', hebrew: 'אוטובוס', concept: 'Bus', provisional: false, provisionalNote: '', strategy: 'Direct Iconic Representation' },
    { id: 'CAT-0017', hebrew: 'שירים', concept: 'Songs / Singing', provisional: true, provisionalNote: 'Representational strategy requires confirmation — may use notation or gesture', strategy: 'Metonymic Association' },
    { id: 'CAT-0018', hebrew: 'מגדת עתידות', concept: 'Fortune teller', provisional: false, provisionalNote: '', strategy: 'Direct Iconic Representation' },
    { id: 'CAT-0019', hebrew: 'אוניה', concept: 'Ship', provisional: false, provisionalNote: '', strategy: 'Direct Iconic Representation' },
    { id: 'CAT-0020', hebrew: 'אתחתן', concept: 'Wedding / Marriage', provisional: true, provisionalNote: 'Verb form — concept label requires confirmation: represents the wedding event', strategy: 'Direct Iconic Representation' },
    { id: 'CAT-0021', hebrew: 'ציפור', concept: 'Bird', provisional: false, provisionalNote: '', strategy: 'Direct Iconic Representation' },
    { id: 'CAT-0022', hebrew: 'תפוזים', concept: 'Oranges', provisional: false, provisionalNote: '', strategy: 'Direct Iconic Representation' },
    { id: 'CAT-0023', hebrew: 'סלע', concept: 'Rock / Boulder', provisional: false, provisionalNote: '', strategy: 'Direct Iconic Representation' },
    { id: 'CAT-0024', hebrew: 'יער', concept: 'Forest', provisional: false, provisionalNote: '', strategy: 'Direct Iconic Representation' },
    { id: 'CAT-0025', hebrew: 'מימייה', concept: 'Canteen / Water bottle', provisional: false, provisionalNote: '', strategy: 'Direct Iconic Representation' },
    { id: 'CAT-0026', hebrew: 'ג׳יפ', concept: 'Jeep', provisional: false, provisionalNote: '', strategy: 'Direct Iconic Representation' },
    { id: 'CAT-0027', hebrew: 'חיילים', concept: 'Soldiers', provisional: false, provisionalNote: '', strategy: 'Direct Iconic Representation' },
    { id: 'CAT-0028', hebrew: 'משכורת', concept: 'Salary / Paycheck', provisional: true, provisionalNote: 'Abstract concept — representational strategy requires confirmation', strategy: 'Metonymic Association' },
    { id: 'CAT-0029', hebrew: 'צבא', concept: 'Army / Military', provisional: true, provisionalNote: 'Representational strategy requires confirmation', strategy: 'Metonymic Association' },
    { id: 'CAT-0030', hebrew: 'רפת', concept: 'Barn / Cowshed', provisional: false, provisionalNote: '', strategy: 'Direct Iconic Representation' },
    { id: 'CAT-0031', hebrew: 'טיול', concept: 'Trip / Hike / Excursion', provisional: false, provisionalNote: '', strategy: 'Direct Iconic Representation' },
    { id: 'CAT-0032', hebrew: 'חליבה', concept: 'Milking', provisional: true, provisionalNote: 'Visual form requires confirmation against the catalog entry', strategy: 'Direct Iconic Representation' },
    { id: 'CAT-0033', hebrew: 'תצפית', concept: 'Lookout / Observation post', provisional: true, provisionalNote: 'Visual form requires confirmation against the catalog entry', strategy: 'Direct Iconic Representation' },
    { id: 'CAT-0034', hebrew: 'עצי זית', concept: 'Olive trees', provisional: false, provisionalNote: '', strategy: 'Direct Iconic Representation' },
  ];
})(typeof globalThis !== 'undefined' ? globalThis : window);
